### ISSUE TITLE
false positives: installation-report

### ISSUE THREAD

**Issue by jdietrch** [a-detiste/cruft-ng#22]
I installed Debian testing using debian-testing-amd64-netinst.iso downloaded from here:
https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/
I also installed cruft-ng 0.9.64.

Running cruft-ng produced a list of unexplained files which included several from `/var/log/installer`:
```
/var/log/installer/cdebconf
/var/log/installer/cdebconf/questions.dat
/var/log/installer/cdebconf/templates.dat
/var/log/installer/firmware-summary
/var/log/installer/hardware-summary
/var/log/installer/lsb-release
/var/log/installer/partman
/var/log/installer/status
/var/log/installer/syslog
```

Now I see that `rules/installation-report` already contains `/var/log/installer`. Does this match only the directory itself and not the files within that directory? If so, then does another line need to be added: `/var/log/installer/*`?

**Comment by a-detiste** [comment]
Hi,

I will check next week

**Comment by a-detiste** [comment]
done
