### ISSUE TITLE
cruft does not report /etc/cruft/ignore file unexplained

### ISSUE THREAD

**Issue by jniggemann** [a-detiste/cruft-ng#23]
Using cruft-ng 0.9.54 on Debian 12.8
I added a file `/etc/cruft/ignore`, but despite `plocate` finding the file, cruft does not report it as "unexplained".

**Comment by jniggemann** [comment]
_"cruft-ng is a program to look over your system for anything that shouldn't be there, but is; or for anything that should be there, but isn't."_

My understanding from reading the above phrase and the Debian manpage was that cruft lists each file that
a) shouldn't be there, but is ("unexplained")
b) should be there but isn't ("missing")

My thinking was: _/etc/cruft/ignore_ is not in the deb package, so cruft will report it as a) "_shouldn't be there, but is_".
Where did I go wrong?

**Comment by a-detiste** [comment]
Well there's a grey zone too.

Some files must be there: the static files registered in dpkg database. Some should not be there: the one in the cruft report. Then there are the dynamic files known from the `rules/` in cruft-ng.

The newer `cpigs` command with it's CSV mode allow to analyse this grey zone. (and/or to feeds the results in Jupyter or whatever)

**Comment by a-detiste** [comment]
The semantics of the `cruft` command have been the same for 20 years, I don't want to change them and make people angry for no reasons.

**Comment by jniggemann** [comment]
> Then there are the dynamic files known from the rules/ in cruft-ng.

Got it, I was missing that part.
