### ISSUE TITLE
dh-cruft uses the debhelper version rather than its own version

### ISSUE THREAD

**Issue by nthykier** [a-detiste/cruft-ng#6]
https://github.com/a-detiste/cruft-ng/blob/1b977cf91598ab5e921f142410ae19eda5ad4bf1/dh-cruft/dh_cruft#L13

The `our $VERSION = DH_BUILTIN_VERSION;` is reserved for debhelper's own tools to substitute in the debhelper version number. The `dh_cruft` tool should use its own version (possibly in the form of the version of cruft-ng).

**Comment by a-detiste** [comment]
It's modified in the build, in a hackish way of course
>  sed -i 's/DH_BUILTIN_VERSION/"$(DEB_VERSION)"/' debian/dh-cruft/usr/bin/dh_cruft
... but I really hope that this tiny, simple plugin would be integrated in DebHelper proper soon
(soon like 2023 is ok)

**Comment by nthykier** [comment]
Fair - had not seen the `sed` during build as a solution (admittedly, I still consider it confusing but if it does the right thing when installed, I suppose it is fine).

**Comment by a-detiste** [comment]
I started from `/usr/bin/dh_lintian` as template ... as it was the smallest script and closest to what I needed.

**Comment by a-detiste** [comment]
ok fixed
