### ISSUE TITLE
Lack of error handling for `open`

### ISSUE THREAD

**Issue by nthykier** [a-detiste/cruft-ng#8]
Perl is (unfortunately) not a language that throws exceptions by default.  Therefore the `open` calls need manually guards:
https://github.com/a-detiste/cruft-ng/blob/1b977cf91598ab5e921f142410ae19eda5ad4bf1/dh-cruft/dh_cruft#L63
https://github.com/a-detiste/cruft-ng/blob/1b977cf91598ab5e921f142410ae19eda5ad4bf1/dh-cruft/dh_cruft#L83

Usually the pattern `open(...) or error("Failed to read ${file}: $!")` will do.

Additionally the `close` in line 88 will also need a guard (as it is open for writing)
https://github.com/a-detiste/cruft-ng/blob/1b977cf91598ab5e921f142410ae19eda5ad4bf1/dh-cruft/dh_cruft#L88

(whether you do it for the line 65 case, is less urgent as close on read tends to never fail for valid input)

**Comment by a-detiste** [comment]
Fixed, thanks !
