### ISSUE TITLE
Should there be a safe-guard for run-off cruft files?

### ISSUE THREAD

**Issue by nthykier** [a-detiste/cruft-ng#9]
It takes one-typo in the cruft file to generate an `rm -fr /usr` disaster based on my reading of https://github.com/a-detiste/cruft-ng/blob/1b977cf91598ab5e921f142410ae19eda5ad4bf1/dh-cruft/dh_cruft#L66-70

Are you sure you do not want some sort of safe-guard to cache "obvious" mistakes like nuking `/usr` due to a space, shell meta character or someone mistakenly wanting to use ${...} substitution?

**Comment by a-detiste** [comment]
Yeah I know .... shame one me... I'd rather to use a whitelist like  "a-zA-Z0-9:-_?*~"
but not the whitespace or `;`.

The % looks weird in a filename.


```
tchet@brix ~/git/cruft-ng $ cat rules/* | grep ^/ | tr -d '/[a-zA-Z0-9:\-\_\*\?\.]' | sort -u

%
~
tchet@brix ~/git/cruft-ng $ grep \% rules/*
rules/gconf2-common:/etc/gconf/gconf.xml.defaults/%gconf-tree.xml
rules/gconf2-common:/etc/gconf/gconf.xml.mandatory/%gconf-tree.xmlgconf/debian.defaults/%gconf-tree.xml
rules/gconf2-common:/var/lib/gconf/defaults/%gconf-tree.xml
rules/gconf2-common:/var/lib/gconf/defaults/%gconf-tree-*.xml
tchet@brix ~/git/cruft-ng $ grep \~ rules/*
rules/apt:/etc/apt/trusted.gpg~
rules/fwupd:/var/lib/fwupd/gnupg/pubring.kbx~
```

**Comment by a-detiste** [comment]
Some sort of substitution could be supported later:
```
$ cat openjdk-11-jre-headless
/usr/lib/jvm/java-11-openjdk-*/lib/client/classes.jsa
/usr/lib/jvm/java-11-openjdk-*/lib/server/classes.jsa
```

**Comment by a-detiste** [comment]
safe guard has been implemented
